#+Title: Makefile

The makefile showing how to compile the project.

#+begin_src Makefile :tangle ../tangled/Makefile :mkdirp yes
CFLAGS = -Wall -Wextra -pedantic -std=c17 -g

common-objects = pane.o undo.o zipperBuffer.o editorRow.o \
          util.o fileData.o display.o $(patsubst %.c,%.o,$(wildcard lists/*.c)) \
          edit.o string.o

test-objects = $(patsubst %.c,%.o,$(wildcard test/*.c)) $(common-objects)

main-objects = kibi.o $(common-objects)

test : $(test-objects)
	cc $(CFLAGS) -o testLists $(test-objects)

kibi : $(main-objects)
	cc $(CFLAGS) -o kibi $(main-objects)

kibi.o: kibi.c editorRow.h fileData.h pane.h undo.h zipperBuffer.h display.h edit.h
zipperBuffer.o: zipperBuffer.c editorRow.h
pane.o: pane.c editorRow.h util.h zipperBuffer.h fileData.h
fileData.o: fileData.c undo.h zipperBuffer.h
display.o: display.c pane.h

.PHONY : clean
clean :
	rm kibi $(objects)
#+end_src
